# Updated Schedule {- #schedule}

I will keep this page with the updated schedule for the semester. You can find these readings on [Blackboard](https://utsa.blackboard.com/ultra/courses/_231735_1/cl/outline).

```{r, echo=FALSE, include=FALSE}
title_line<-"| Week| Session | Topic| Required reading| Method| Deliverable | \n"
separation_line<-"| -- | -- | -- | -- | -- | -- | \n"
create_session<- function(vector){
  week<-vector[1]
  session<-vector[2]
  topic<-vector[3]
  reading<-vector[4]
  method<-vector[5]
  deliverable<-vector[6]

  line<-paste0(c("|",week,"|",session,"|",topic,"|",reading,"|",method,"|",deliverable, "|", "\n"))
}
s_intro<-c("1: 08/22", "1", "Introduction to the course", " ", " ", " ")
s_geomob<-c("1: 08/24", #date
           "2", # session
           "[Geography of Upward Mobility in America](#lec1_geomobility)", #topic with link
           "Chetty, Friedman, Hendren, Jones and Porter (2018)- **Non-technical summary** ", #reading
           " ", # method
           " ") #deliverable
s_introR<-c("2: 08/29", #date
           "3", # session
           "[Intro to R and data](#getting-started)", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_introR2<-c("2: 08/31", #date
           "4", # session
           "Intro to [Visualization](#viz), [Wrangling](#wrangling) and [RMarkdown](#rmarkdown)", #topic with link
           " ", #reading
           " ", # method
           "First short report (In class)") #deliverable
s_laborday<-c("3: 09/05", #date
           "-", # session
           "Labor Day – No class", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_causaleffects<-c("3: 09/07", #date
           "5", # session
           "[Intro to Causal Effects of Neighborhoods](#lec2_causaleffect) ", #topic with link
           "Bergman, Chetty, DeLuca, Hendren, Katz and Palmer (2019) **[Non-technical summary]**", #reading
           "Experiments (RCTs)", # method
           "[Project 1](#project1) – Part 1") #deliverable
s_causaleffects2<-c("4: 09/12", #date
           "6", # session
           "[Characteristics of High-Mobility Areas](#lec2_causaleffect) and [Correlation Analysis](#regression) ", #topic with link
           "Bergman, Chetty, DeLuca, Hendren, Katz and Palmer (2019) - Introduction", #reading
           "Quasi-experiments ", # method
           " ") #deliverable
s_mto<-c("4: 09/14", #date
           "7", # session
           "[Moving to Opportunity and place based policies](#lec3_mto-placebased) ", #topic with link
           " ", #reading
           "Cost-benefit analysis ", # method
           "[Project 1](#project1) – Part 1 and 2 (for Friday 09/16) ") #deliverable
s_mob_hist_int<-c("5: 09/19", #date
           "8", # session
           "[Historical and International Evidence on](#lec4_mob-hist-int) and [Drivers of Inequality and Mobility](#lec4_mob-hist-int) ", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_mob_ed<-c("5: 09/21", #date
           "9", # session
           "[Higher Education and Upward Mobility](#lec5_mob-ed) ", #topic with link
           "Dynarski, Libassi, Michelmore and Owen (2018) ", #reading
           "Regression discontinuity ", # method
           " ") #deliverable
s_ed_higher<-c("6: 09/26", #date
           "10", # session
           "[Causal Effects of Higher Education](#lec6_ed-higher) ", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_review_mid<-c("6: 09/28", #date
           "11", # session
           "Review for midterm ", #topic with link
           " ", #reading
           " ", # method
           "[Project 2](#project2) (Friday 09/30) ") #deliverable
s_mid<-c("7: 10/03", #date
           "12", # session
           "**Midterm**  ", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_solution_mid<-c("7: 10/05", #date
           "13", # session
           "_Solution review_  ", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_recap_quarto<-c("8: 10/10", #date
           "14", # session
           "Recap of R and Quarto Documents ", #topic with link
           " ", #reading
           " ", # method
           " ") #deliverable
s_k12<-c("8: 10/12", #date
           "15", # session
           "[Primary education](#lec7_k12)", #topic with link
           "Chetty, Friedman and Rockoff (2011) [Non-technical summary]	", #reading
           "Experiments ", # method
           " ") #deliverable
s_teachers<-c("9: 10/17", #date
           "16", # session
           "[Teachers and Charter Schools](#lec8_teachers-charters)", #topic with link
           "	", #reading
           "Event study designs, competitive equilibrium ", # method
           " ") #deliverable
s_racedis<-c("9: 10/19", #date
           "17", # session
           "[Racial Disparities in Economic Opportunity](#lec9_race-ineq) ", #topic with link
           "Bertrand, and Mullainathan (2004)	", #reading
           "Dynamic models and steady states ", # method
           " ") #deliverable
s_mediabias<-c("10: 10/24", #date
           "18", # session
           "Media Bias in Crime Coverage and Housing Prices ", #topic with link
           "  ", #reading
           "Instrumental Variables", # method
           " ") #deliverable
s_jud_sys<-c("10: 10/26", #date
           "19", # session
           "[Improving judicial decisions](#lec10_criminal-justice)", #topic with link
           "Kleinberg, Lakkaraju, Leskovec, Ludwig and Mullainathan (2017) ", #reading
           "Machine learning, implicit bias ", # method
           "") #deliverable
s_immigration<-c("11: 10/31", #date
           "20", # session
           "Immigration ", #topic with link
           "Clemens (2011)  ", #reading
           "Welfare analysis ", # method
           "[Project 3](#project3)") #deliverable
s_ml<-c("11: 10/02", #date
           "21", # session
           "Implementing a simple machine learning model in R - Part 1", #topic with link
           "  ", #reading
           "  ", # method
           " ") #deliverable
s_ml2<-c("12: 11/07", #date
           "22", # session
           "Implementing a simple machine learning model in R - Part 2", #topic with link
           "  ", #reading
           "  ", # method
           " ") #deliverable
s_ml3<-c("12: 11/09", #date
           "23", # session
           "Implementing a simple machine learning model in R - Part 3", #topic with link
           "  ", #reading
           "  ", # method
           " ") #deliverable
s_polecon<-c("13: 11/14", #date
           "24", # session
           "Political Economy ", #topic with link
           "  ", #reading
           " ", # method
           "") #deliverable
s_noclass<-c("13: 11/16", #date
           "-", # session
           "-", #topic with link
           "", #reading
           "", # method
           " ") #deliverable
s_tax<-c("14: 11/21", #date
           "25", # session
           "Income taxation ", #topic with link
           "Diamond and Saez (2011)  ", #reading
           "Supply and demand; synthetic control ", # method
           " ") #deliverable
s_saving<-c("15: 11/28", #date
           "26", # session
           "Savings and wealth ", #topic with link
           "  ", #reading
           "Behavioral Economics ", # method
           " ") #deliverable
# s_housing<-c("13: 11/16", #date
#            "25", # session
#            "Housing markets and COVID ", #topic with link
#            "Glaeser, Edward, Kominers, Luca and Naik (2018)   ", #reading
#            " ", # method
#            "Project 4 – Part 1") #deliverable
# s_pollution<-c("14: 11/21", #date
#            "26", # session
#            "Intro to air and water pollution, and externalities ", #topic with link
#            "Moore, Obradovich, Lehner and Baylis (2019)   ", #reading
#            "Difference in difference ", # method
#            " ") #deliverable
# s_discountrate<-c("14: 11/23", #date
#            "27", # session
#            "Discount rates, external validity ", #topic with link
#            " ", #reading
#            "Difference in difference ", # method
#            "Project 4 – Part 1 and 2") #deliverable
# s_tbd1<-c("15: 11/28", #date
#            "28", # session
#            "TBD 1 ", #topic with link
#            " ", #reading
#            " ", # method
#            " ") #deliverable
s_review_final<-c("15: 11/30", #date
           "27", # session
           "Review session ", #topic with link
           " ", #reading
           " ", # method
           "[Project 4](#project4) - (for Friday 12/02)") #deliverable
```

```{r tableSchedule, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
# tabl <- "
# | Week              | Session | Topic                                                                              | Required reading                                                                       | Method                                       | Deliverable                   |
# | --------------------- | ------- | ---------------------------------------------------------------------------------- |  -------------------------------------------------------------------------------------- |  -------------------------------------------- | ----------------------------- |
# | 1: 08/22 & 08/24  | 1       | Introduction to the course                                                         |                                                                                        |                                              |                               |
# |                   | 2       | [Geography of Upward Mobility in America](#lec1_geomobility)                                            | Chetty, Friedman, Hendren, Jones and Porter (2018)- **Non-technical summary**      | Correlation, regression                      |                               |
# | 2: 08/29 & 08/31  | 3       | [Intro to R and data](#getting-started)                                                                |                                                                                        |                                              |                               |
# |                   | 4       | Intro to [Visualization](#viz), [Wrangling](#wrangling) and [RMarkdown](#rmarkdown)                                    |                                                                                        |                                              | First short report (In class) |
# | 3: 09/05 & 09/07  | -      | Labor Day – No class                                                               |                                                                                        |                                              |                               |
# |                   | 5       | [Intro to Causal Effects of Neighborhoods](#lec2_causaleffect)                                           | Bergman, Chetty, DeLuca, Hendren, Katz and Palmer (2019) **[Non-technical summary]** | Experiments (RCTs)                           | [Project 1](#project1) – Part 1            |
# | 4: 09/12 & 09/14  | 6       | [Characteristics of High-Mobility Areas](#lec2_causaleffect) and [Correlation Analysis](#regression)                                            | Bergman, Chetty, DeLuca, Hendren, Katz and Palmer (2019) - Introduction              | Quasi-experiments                            |                               |
# |                   | 7       | [Moving to Opportunity and place based policies](#lec3_mto-placebased)  |                                                                                        | Cost-benefit analysis                        | [Project 1](#project1) – Part 2 (for Friday 09/16)           |
# | 5: 09/19 & 09/21  | 8       | [Historical and International Evidence on](#lec4_mob-hist-int)<br>[the Drivers of Inequality and Mobility](#lec4_mob-hist-int)                                            |                                                         |                  |                               |
# |                   | 9       | [Higher Education and Upward Mobility](#lec5_mob-ed)                                               | Dynarski, Libassi, Michelmore and Owen (2018)                                          | Regression discontinuity                     |                               |
# | 6: 09/26 & 09/28  | 10      | [Causal Effects of Higher Education](#lec6_ed-higher)                                            |                                                                                        |                                              |                               |
# |                   | 11      | Review for midterm                                                                 |                                                                                        |                                              | [Project 2](#project2) (Friday 09/30)                    |
# | 7: 10/03 & 10/05  | 12      | **Midterm**                                                                        |                                                                                        |                                              |                               |
# |                   | 13      | _Solution review_                                                                  |                                                                                        |                                              |                               |
# | 8: 10/10 & 10/12  | 14      | Recap of R and Quarto Documents                                                     | Chetty, Friedman and Rockoff (2011) **[Non-technical summary]**                      | Experiments                                  |                               |
# |                   | 15      | Teachers and Charter Schools                                                       |                                                                                        | Event study designs, competitive equilibrium |                               |
# | 9: 10/17 & 10/19  | 16      | Racial Disparities in Economic Opportunity                                         | Bertrand, and Mullainathan (2004)                                                      | Dynamic models and steady states             |                               |
# |                   | 17      | Improving judicial decisions                                                       | Kleinberg, Lakkaraju, Leskovec, Ludwig and Mullainathan (2017)                         | Machine learning, implicit bias              | Project 3                     |
# | 10: 10/24 & 10/26 | 18      | Implementing a simple machine learning model in R                                  |                                                                                        |                                              |                               |
# |                   | 19      | Immigration                                                                        | Clemens (2011)                                                                         | Welfare analysis                             |                               |
# | 11: 10/31 & 11/02 | 20      | Political Economy                                                                  |                                                                                        |                                              |                               |
# |                   | 21      | Income taxation                                                                    | Diamond and Saez (2011)                                                                | Supply and demand; synthetic control         |                               |
# | 12: 11/07& 11/09  | 22      | Savings and wealth                                                                 |                                                                                        | Behavioral economics                         |                               |
# |                   | 23      |                                                                                    |                                                                                        | Regression                                   | Project 4 – Part 1            |
# | 13: 11/14 & 11/16 | 24      | Housing markets and COVID                                                          | Glaeser, Edward, Kominers, Luca and Naik (2018)                                        | Machine learning                             |                               |
# |                   | 25      | Intro to air and water pollution, and externalities                                | Moore, Obradovich, Lehner and Baylis (2019)                                            | Difference in difference                     | Project 4 – Part 2            |
# | 14: 11/21 & 11/28 | 26      | Discount rates, external validity                                                  |                                                                                        | Regression discontinuity                     |                               |
# |                   | 27      |                                                                                    |                                                                                        |                                              |                               |
# | 15: 11/28 & 11/30 | 28      |                                                                                    |                                                                                        |                                              |                               |
# |                   | 29      | Review session                                                                     |                                                                                        |                                              |                               |
# | 16: 12/05 -12-09  | -      | Final Exam Week                                                                    |                                                                                        |                                              |                               |
# |                   | -      |                                                                                    |                                                                                        |                                              |                               |
# "
tabl<-paste0(c(title_line,
               separation_line, 
               create_session(s_intro),
               create_session(s_geomob), 
              create_session(s_introR), 
              create_session(s_introR2), 
              create_session(s_laborday), 
              create_session(s_causaleffects), 
              create_session(s_causaleffects2), 
              create_session(s_mto), 
              create_session(s_mob_hist_int), 
              create_session(s_mob_ed), 
              create_session(s_ed_higher), 
              create_session(s_review_mid), 
              create_session(s_mid), 
              create_session(s_solution_mid), 
              create_session(s_recap_quarto), 
              create_session(s_k12), 
              create_session(s_teachers), 
              create_session(s_racedis), 
              create_session(s_mediabias),
              create_session(s_jud_sys), 
              create_session(s_immigration), 
              create_session(s_ml), 
              create_session(s_ml2), 
              create_session(s_ml3), 
              create_session(s_polecon),
              create_session(s_noclass),
              create_session(s_tax), 
              create_session(s_saving), 
              #create_session(s_housing),
              #create_session(s_pollution),
              #create_session(s_discountrate),
              #create_session(s_tbd1),
              create_session(s_review_final)))
cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```


