<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Simple and Multivariate Regression | Economics of Public and Social Issues</title>
  <meta name="description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2022." />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Simple and Multivariate Regression | Economics of Public and Social Issues" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2022." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Simple and Multivariate Regression | Economics of Public and Social Issues" />
  
  <meta name="twitter:description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2022." />
  

<meta name="author" content="Jonathan Moreno-Medina" />


<meta name="date" content="2022-09-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="wrangling.html"/>
<link rel="next" href="rmarkdown.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Eco of Public and Social Issues (ECO 3253), Fall 2022</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aboutme"><i class="fa fa-check"></i>About me</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#organization-of-this-site"><i class="fa fa-check"></i>Organization of this site</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-driven-course"><i class="fa fa-check"></i>Data-driven course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#topics-to-be-covered"><i class="fa fa-check"></i>Topics to be covered</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#statistical-tools"><i class="fa fa-check"></i>Statistical tools</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#economic-concepts"><i class="fa fa-check"></i>Economic Concepts</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#projects"><i class="fa fa-check"></i>Projects</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#faqs"><i class="fa fa-check"></i>FAQs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Updated Schedule</a></li>
<li class="part"><span><b>I Ec. &amp; Soc. Issues</b></span></li>
<li class="chapter" data-level="1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html"><i class="fa fa-check"></i><b>1</b> Upward Mobility in the US</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#parental-and-children-income-rank"><i class="fa fa-check"></i><b>1.1</b> Parental and children income rank</a></li>
<li class="chapter" data-level="1.2" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#interpreting-the-regression-line"><i class="fa fa-check"></i><b>1.2</b> Interpreting the regression line</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#percentiles"><i class="fa fa-check"></i><b>1.2.1</b> Percentiles</a></li>
<li class="chapter" data-level="1.2.2" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#what-is-a-tract"><i class="fa fa-check"></i><b>1.2.2</b> What is a tract?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#geographic-variation-in-upward-mobility-by-commuting-zone"><i class="fa fa-check"></i><b>1.3</b> Geographic Variation in Upward Mobility by Commuting Zone</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#adjustments-for-cost-of-living"><i class="fa fa-check"></i><b>1.3.1</b> Adjustments for cost of living</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#local-area-variation-in-upward-mobility-los-angeles-ca"><i class="fa fa-check"></i><b>1.4</b> Local Area Variation in Upward Mobility: Los Angeles, CA</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="causaleffect.html"><a href="causaleffect.html"><i class="fa fa-check"></i><b>2</b> The Causal Effect of Neighborhoods</a>
<ul>
<li class="chapter" data-level="2.1" data-path="causaleffect.html"><a href="causaleffect.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="causaleffect.html"><a href="causaleffect.html#causal-effects-of-neighborhoods-vs.-sorting"><i class="fa fa-check"></i><b>2.2</b> Causal Effects of Neighborhoods vs. Sorting</a></li>
<li class="chapter" data-level="2.3" data-path="causaleffect.html"><a href="causaleffect.html#identifying-causal-effects-of-neighborhoods"><i class="fa fa-check"></i><b>2.3</b> Identifying Causal Effects of Neighborhoods</a></li>
<li class="chapter" data-level="2.4" data-path="causaleffect.html"><a href="causaleffect.html#stating-and-assessing-the-identification-assumption-for-the-movers-research-design"><i class="fa fa-check"></i><b>2.4</b> Stating and assessing the identification assumption for the movers research design</a></li>
<li class="chapter" data-level="2.5" data-path="causaleffect.html"><a href="causaleffect.html#why-does-upward-mobility-differ-across-areas"><i class="fa fa-check"></i><b>2.5</b> Why Does Upward Mobility Differ Across Areas?</a></li>
<li class="chapter" data-level="2.6" data-path="causaleffect.html"><a href="causaleffect.html#the-five-strongest-correlates-of-upward-mobility"><i class="fa fa-check"></i><b>2.6</b> The Five Strongest Correlates of Upward Mobility</a></li>
<li class="chapter" data-level="2.7" data-path="causaleffect.html"><a href="causaleffect.html#policy-interest-in-increasing-upward-mobility"><i class="fa fa-check"></i><b>2.7</b> Policy Interest in Increasing Upward Mobility</a></li>
<li class="chapter" data-level="2.8" data-path="causaleffect.html"><a href="causaleffect.html#policies-to-improve-upward-mobility"><i class="fa fa-check"></i><b>2.8</b> Policies to Improve Upward Mobility</a></li>
<li class="chapter" data-level="2.9" data-path="causaleffect.html"><a href="causaleffect.html#affordable-housing-policies-in-the-united-states"><i class="fa fa-check"></i><b>2.9</b> Affordable Housing Policies in the United States</a></li>
<li class="chapter" data-level="2.10" data-path="causaleffect.html"><a href="causaleffect.html#a-framework-for-studying-the-effects-of-housing-vouchers"><i class="fa fa-check"></i><b>2.10</b> A Framework for Studying the Effects of Housing Vouchers</a></li>
<li class="chapter" data-level="2.11" data-path="causaleffect.html"><a href="causaleffect.html#randomized-experiments"><i class="fa fa-check"></i><b>2.11</b> Randomized Experiments</a></li>
<li class="chapter" data-level="2.12" data-path="causaleffect.html"><a href="causaleffect.html#non-compliance-in-randomized-experiments"><i class="fa fa-check"></i><b>2.12</b> Non-Compliance in Randomized Experiments</a></li>
</ul></li>
<li class="part"><span><b>II Tools</b></span></li>
<li class="chapter" data-level="3" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>3</b> Very Brief Intro to Data in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="getting-started.html"><a href="getting-started.html#why-r-again"><i class="fa fa-check"></i><b>3.1</b> Why R again?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="getting-started.html"><a href="getting-started.html#why-are-we-learning-r-i-wanted-to-learn-about-economics-of-public-and-social-issues"><i class="fa fa-check"></i><b>3.1.1</b> Why are we learning R? I wanted to learn about economics of public and social issues…</a></li>
<li class="chapter" data-level="3.1.2" data-path="getting-started.html"><a href="getting-started.html#ok-but-why-r"><i class="fa fa-check"></i><b>3.1.2</b> Ok, but why R?</a></li>
<li class="chapter" data-level="3.1.3" data-path="getting-started.html"><a href="getting-started.html#added-benefits-of-learning-r"><i class="fa fa-check"></i><b>3.1.3</b> Added benefits of learning R</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="getting-started.html"><a href="getting-started.html#key-concepts-before-we-start"><i class="fa fa-check"></i><b>3.2</b> Key concepts before we start:</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="getting-started.html"><a href="getting-started.html#r-rstudio"><i class="fa fa-check"></i><b>3.2.1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="3.2.2" data-path="getting-started.html"><a href="getting-started.html#r-and-rstudio-in-your-computer-or-in-the-cloud"><i class="fa fa-check"></i><b>3.2.2</b> R and RStudio: In your computer or in the cloud?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="getting-started.html"><a href="getting-started.html#lets-open-r"><i class="fa fa-check"></i><b>3.3</b> Let’s open R!</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="getting-started.html"><a href="getting-started.html#rstudio-in-the-cloud"><i class="fa fa-check"></i><b>3.3.1</b> RStudio in the cloud</a></li>
<li class="chapter" data-level="3.3.2" data-path="getting-started.html"><a href="getting-started.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>3.3.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="getting-started.html"><a href="getting-started.html#code"><i class="fa fa-check"></i><b>3.4</b> How do I code in R?</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="getting-started.html"><a href="getting-started.html#programming-concepts"><i class="fa fa-check"></i><b>3.4.1</b> Basic programming concepts and terminology</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="getting-started.html"><a href="getting-started.html#in-class-exercise"><i class="fa fa-check"></i><b>3.5</b> In Class Exercise</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="getting-started.html"><a href="getting-started.html#errors-warnings-and-messages"><i class="fa fa-check"></i><b>3.5.1</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="3.5.2" data-path="getting-started.html"><a href="getting-started.html#tips-on-learning-to-code"><i class="fa fa-check"></i><b>3.5.2</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>3.6</b> What are R packages?</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="getting-started.html"><a href="getting-started.html#package-installation"><i class="fa fa-check"></i><b>3.6.1</b> Package installation</a></li>
<li class="chapter" data-level="3.6.2" data-path="getting-started.html"><a href="getting-started.html#package-loading"><i class="fa fa-check"></i><b>3.6.2</b> Package loading</a></li>
<li class="chapter" data-level="3.6.3" data-path="getting-started.html"><a href="getting-started.html#package-use"><i class="fa fa-check"></i><b>3.6.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="getting-started.html"><a href="getting-started.html#hands-on-exercise"><i class="fa fa-check"></i><b>3.7</b> Hands-on exercise!</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="getting-started.html"><a href="getting-started.html#mobilitydata"><i class="fa fa-check"></i><b>3.7.1</b> Explore your first dataset: economic mobility in the US</a></li>
<li class="chapter" data-level="3.7.2" data-path="getting-started.html"><a href="getting-started.html#economic-mobility-data"><i class="fa fa-check"></i><b>3.7.2</b> Economic mobility data</a></li>
<li class="chapter" data-level="3.7.3" data-path="getting-started.html"><a href="getting-started.html#atlas-data-frame"><i class="fa fa-check"></i><b>3.7.3</b> <code>atlas</code> data frame</a></li>
<li class="chapter" data-level="3.7.4" data-path="getting-started.html"><a href="getting-started.html#exploredataframes"><i class="fa fa-check"></i><b>3.7.4</b> Exploring data frames</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="getting-started.html"><a href="getting-started.html#conclusion"><i class="fa fa-check"></i><b>3.8</b> Conclusion</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="getting-started.html"><a href="getting-started.html#additional-resources"><i class="fa fa-check"></i><b>3.8.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="" data-path="viz.html"><a href="viz.html#needed-data-and-packages"><i class="fa fa-check"></i>Needed data and packages</a></li>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#grammarofgraphics"><i class="fa fa-check"></i><b>4.1</b> The Grammar of Graphics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="viz.html"><a href="viz.html#components-of-the-grammar"><i class="fa fa-check"></i><b>4.1.1</b> Components of the Grammar</a></li>
<li class="chapter" data-level="4.1.2" data-path="viz.html"><a href="viz.html#gapminder"><i class="fa fa-check"></i><b>4.1.2</b> Gapminder data</a></li>
<li class="chapter" data-level="4.1.3" data-path="viz.html"><a href="viz.html#other-components"><i class="fa fa-check"></i><b>4.1.3</b> Other components</a></li>
<li class="chapter" data-level="4.1.4" data-path="viz.html"><a href="viz.html#ggplot2-package"><i class="fa fa-check"></i><b>4.1.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#FiveNG"><i class="fa fa-check"></i><b>4.2</b> Three Important Graphs -</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#scatterplots"><i class="fa fa-check"></i><b>4.3</b> Scatterplots</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="viz.html"><a href="viz.html#geompoint"><i class="fa fa-check"></i><b>4.3.1</b> Scatterplots via geom_point</a></li>
<li class="chapter" data-level="4.3.2" data-path="viz.html"><a href="viz.html#overplotting"><i class="fa fa-check"></i><b>4.3.2</b> Over-plotting</a></li>
<li class="chapter" data-level="4.3.3" data-path="viz.html"><a href="viz.html#summary"><i class="fa fa-check"></i><b>4.3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#histograms"><i class="fa fa-check"></i><b>4.4</b> Histograms</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="viz.html"><a href="viz.html#geomhistogram"><i class="fa fa-check"></i><b>4.4.1</b> Histograms via geom_histogram</a></li>
<li class="chapter" data-level="4.4.2" data-path="viz.html"><a href="viz.html#adjustbins"><i class="fa fa-check"></i><b>4.4.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="4.4.3" data-path="viz.html"><a href="viz.html#summary-1"><i class="fa fa-check"></i><b>4.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#geombar"><i class="fa fa-check"></i><b>4.5</b> Barplots</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>4.5.1</b> Barplots via geom_bar or geom_col</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#summary-2"><i class="fa fa-check"></i><b>4.5.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#conclusion-1"><i class="fa fa-check"></i><b>4.6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="viz.html"><a href="viz.html#summary-table"><i class="fa fa-check"></i><b>4.6.1</b> Summary table</a></li>
<li class="chapter" data-level="4.6.2" data-path="viz.html"><a href="viz.html#argument-specification"><i class="fa fa-check"></i><b>4.6.2</b> Argument specification</a></li>
<li class="chapter" data-level="4.6.3" data-path="viz.html"><a href="viz.html#additional-resources-1"><i class="fa fa-check"></i><b>4.6.3</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>5</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="" data-path="wrangling.html"><a href="wrangling.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="5.1" data-path="wrangling.html"><a href="wrangling.html#piping"><i class="fa fa-check"></i><b>5.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.2" data-path="wrangling.html"><a href="wrangling.html#filter"><i class="fa fa-check"></i><b>5.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="5.3" data-path="wrangling.html"><a href="wrangling.html#mutate"><i class="fa fa-check"></i><b>5.3</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="5.4" data-path="wrangling.html"><a href="wrangling.html#other-verbs"><i class="fa fa-check"></i><b>5.4</b> Other verbs</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="wrangling.html"><a href="wrangling.html#select"><i class="fa fa-check"></i><b>5.4.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="5.4.2" data-path="wrangling.html"><a href="wrangling.html#rename"><i class="fa fa-check"></i><b>5.4.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="5.4.3" data-path="wrangling.html"><a href="wrangling.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>5.4.3</b> <code>top_n</code> values of a variable</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="wrangling.html"><a href="wrangling.html#conclusion-2"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="wrangling.html"><a href="wrangling.html#additional-resources-2"><i class="fa fa-check"></i><b>5.5.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>6</b> Simple and Multivariate Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="regression.html"><a href="regression.html#model1"><i class="fa fa-check"></i><b>6.1</b> One numerical explanatory variable</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="regression.html"><a href="regression.html#model1EDA"><i class="fa fa-check"></i><b>6.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="6.1.2" data-path="regression.html"><a href="regression.html#model1table"><i class="fa fa-check"></i><b>6.1.2</b> Simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="regression.html"><a href="regression.html#related-topics"><i class="fa fa-check"></i><b>6.2</b> Related topics</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="regression.html"><a href="regression.html#correlationcoefficient"><i class="fa fa-check"></i><b>6.2.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="6.2.2" data-path="regression.html"><a href="regression.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>6.2.2</b> Correlation is not necessarily causation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="regression.html"><a href="regression.html#model3"><i class="fa fa-check"></i><b>6.3</b> Two numerical explanatory variables</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="regression.html"><a href="regression.html#model3EDA"><i class="fa fa-check"></i><b>6.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="6.3.2" data-path="regression.html"><a href="regression.html#model3table"><i class="fa fa-check"></i><b>6.3.2</b> Regression plane</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="regression.html"><a href="regression.html#how-to-read-p-values"><i class="fa fa-check"></i><b>6.4</b> How to read p-values</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="regression.html"><a href="regression.html#an-example"><i class="fa fa-check"></i><b>6.4.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="regression.html"><a href="regression.html#conclusion-3"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="regression.html"><a href="regression.html#additional-resources-basic-regression"><i class="fa fa-check"></i><b>6.5.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>7</b> RMarkdown / Quarto output</a>
<ul>
<li class="chapter" data-level="7.1" data-path="rmarkdown.html"><a href="rmarkdown.html#how-to-create-an-output-file"><i class="fa fa-check"></i><b>7.1</b> How to create an output file</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="rmarkdown.html"><a href="rmarkdown.html#error-when-rendering-file"><i class="fa fa-check"></i><b>7.1.1</b> Error when rendering file</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="rmarkdown.html"><a href="rmarkdown.html#add-new-code"><i class="fa fa-check"></i><b>7.2</b> Add new code</a></li>
<li class="chapter" data-level="7.3" data-path="rmarkdown.html"><a href="rmarkdown.html#add-a-title"><i class="fa fa-check"></i><b>7.3</b> Add a title</a></li>
<li class="chapter" data-level="7.4" data-path="rmarkdown.html"><a href="rmarkdown.html#add-an-image"><i class="fa fa-check"></i><b>7.4</b> Add an image</a></li>
<li class="chapter" data-level="7.5" data-path="rmarkdown.html"><a href="rmarkdown.html#submit-your-work"><i class="fa fa-check"></i><b>7.5</b> Submit your work</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a>
<ul>
<li class="chapter" data-level="A.1" data-path="appendixA.html"><a href="appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="appendixA.html"><a href="appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="appendixA.html"><a href="appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="appendixA.html"><a href="appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="appendixA.html"><a href="appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="appendixA.html"><a href="appendixA.html#appPercentiles"><i class="fa fa-check"></i><b>A.1.5</b> Percentiles or rank</a></li>
<li class="chapter" data-level="A.1.6" data-path="appendixA.html"><a href="appendixA.html#appDistributions"><i class="fa fa-check"></i><b>A.1.6</b> Distribution</a></li>
<li class="chapter" data-level="A.1.7" data-path="appendixA.html"><a href="appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.7</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Projects</b></span></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html"><i class="fa fa-check"></i>Project 1</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#stories-from-the-atlas-describing-data-using-maps-regressions-and-correlations"><i class="fa fa-check"></i>Stories from the Atlas: Describing Data using Maps, Regressions, and Correlations</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#instructions"><i class="fa fa-check"></i>Instructions</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#specific-questions-to-address-in-your-narrative"><i class="fa fa-check"></i>Specific questions to address in your narrative</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#description"><i class="fa fa-check"></i>Data Description</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#cheatsheetproject1"><i class="fa fa-check"></i>Cheatsheat commands</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#unweighted-summary-statistics"><i class="fa fa-check"></i>Unweighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#load-package"><i class="fa fa-check"></i>Load package</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#weighted-summary-statistics"><i class="fa fa-check"></i>Weighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#subset-observations"><i class="fa fa-check"></i>Subset observations</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#standardize-variables"><i class="fa fa-check"></i>Standardize variables</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#run-regression"><i class="fa fa-check"></i>Run regression</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#how-to-read-the-regression-output"><i class="fa fa-check"></i>How to read the regression output?</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#plotting-the-linear-relationship"><i class="fa fa-check"></i>Plotting the linear relationship</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.jmorenomedina.com/" target="blank">By Jon Moreno-Medina</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Economics of Public and Social Issues</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Simple and Multivariate Regression<a href="regression.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--
Let's briefly recap where we have been so far and where we are headed.  In Chapter \@ref(tidy), we discussed what it means for data to be tidy.  We saw that this refers to observations corresponding to rows and variables being stored in columns (one variable for every column).  The entries in the data frame correspond to different combinations of observations (specific instances of observational units) and variables.  In the `flights` data frame, we saw that each row corresponds to a different flight leaving New York City.  In other words, the **observational unit** of the `flights` tidy data frame is a flight.  The variables are listed as columns, and for `flights` these columns include both quantitative variables like `dep_delay` and `distance` and also categorical variables like `carrier` and `origin`.  An entry in the table corresponds to a particular flight on a given day and a particular value of a given variable representing that flight.
-->
<blockquote>
<p>As a reminder, this is not a course on econometrics, so I will not delve deep into the issues of regression. Nonetheless, there are basic intuitions we can construct when analyzing the data with these models. I will summarize the main issues in this chapter. Nonetheless, feel free to dive deeper <a href="https://nustat.github.io/intro-stat-ds/5-regression.html">here</a>.</p>
</blockquote>
<p>Now that we are equipped with data visualization skills from Chapter <a href="viz.html#viz">4</a>, and data wrangling skills from Chapter <a href="wrangling.html#wrangling">5</a>, we now proceed with data modeling. The fundamental premise of data modeling is <em>to make explicit the relationship</em> between:</p>
<ul>
<li>an outcome variable <span class="math inline">\(y\)</span>, also called a dependent variable and</li>
<li>an explanatory/predictor variable <span class="math inline">\(x\)</span>, also called an independent variable or covariate.</li>
</ul>
<p>Another way to state this is using mathematical terminology: we will model the outcome variable <span class="math inline">\(y\)</span> <em>as a function</em> of the explanatory/predictor variable <span class="math inline">\(x\)</span>. Why do we have two different labels, explanatory and predictor, for the variable <span class="math inline">\(x\)</span>? That’s because roughly speaking data modeling can be used for two purposes:</p>
<ol style="list-style-type: decimal">
<li><strong>Modeling for prediction</strong>: You want to predict an outcome variable <span class="math inline">\(y\)</span> based on the information contained in a set of predictor variables. You don’t care so much about understanding how all the variables relate and interact, but so long as you can make good predictions about <span class="math inline">\(y\)</span>, you’re fine. For example, if we know many individuals’ risk factors for lung cancer, such as smoking habits and age, can we predict whether or not they will develop lung cancer? Here we wouldn’t care so much about distinguishing the degree to which the different risk factors contribute to lung cancer, but instead only on whether or not they could be put together to make reliable predictions.</li>
<li><strong>Modeling for explanation</strong>: You want to explicitly describe the relationship between an outcome variable <span class="math inline">\(y\)</span> and a set of explanatory variables, determine the significance of any found relationships, and have measures summarizing these. Continuing our example from above, we would now be interested in describing the individual effects of the different risk factors and quantifying the magnitude of these effects. One reason could be to design an intervention to reduce lung cancer cases in a population, such as targeting smokers of a specific age group with an advertisement for smoking cessation programs. In this course, we’ll focus more on this latter purpose.</li>
</ol>
<p>Data modeling is used in a wide variety of fields, including statistical inference, causal inference, artificial intelligence, and machine learning. There are many techniques for data modeling, such as tree-based models, neural networks and deep learning, and supervised learning. We will briefly touch on those at the end of the course. For now, we’ll focus on one particular technique: <em>linear regression</em>, one of the most commonly-used and easy-to-understand approaches to modeling. Recall our discussion in Subsection <a href="getting-started.html#exploredataframes">3.7.4</a> on numerical and categorical variables. Linear regression involves:</p>
<ul>
<li>an outcome variable <span class="math inline">\(y\)</span> that is <em>numerical</em> and</li>
<li>explanatory variables <span class="math inline">\(x_i\)</span> (e.g. <span class="math inline">\(x_1, x_2, ...\)</span>) that are either <em>numerical</em> or <em>categorical</em>.</li>
</ul>
<p>With linear regression there is always only one numerical outcome variable <span class="math inline">\(y\)</span> but we have choices on both the number and the type of explanatory variables to use. We’re going to cover the following regression scenarios:</p>
<ul>
<li>Only one explanatory variable: <em>simple linear regression</em>
<ul>
<li>In Section <a href="regression.html#model1">6.1</a>, this explanatory variable will be a single numerical explanatory variable <span class="math inline">\(x\)</span>.<br />
</li>
<li>In the next Section on Experiments we will use an explanatory variable that is a categorical explanatory variable <span class="math inline">\(x\)</span> (being in a treatment or in a control). This is an example of a broader class of regressions using explanatory variables, but we will see those later.</li>
</ul></li>
<li>More than one explanatory variable: <em>multiple regression</em>
<ul>
<li>We’ll focus on two numerical explanatory variables, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, in Section <a href="regression.html#model3">6.3</a>.</li>
<li>We’ll use one numerical and one categorical explanatory variable. As before, we will see this in later sections.</li>
</ul></li>
</ul>
<p>We’ll study the first of each of these two types of regression scenarios using the <code>atlas</code> data! <!--We will also discuss the concept of *correlation* and how it is frequently incorrectly used to imply *causation*.--></p>
<div id="needed-packages-1" class="section level3 unnumbered hasAnchor">
<h3>Needed packages<a href="regression.html#needed-packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now load all the packages needed for this chapter (this assumes you’ve already installed them). In this chapter we introduce some new packages:</p>
<ol style="list-style-type: decimal">
<li>The <code>tidyverse</code> “umbrella” package. You can load the <code>tidyverse</code> package by running <code>library(tidyverse)</code>, which loads several other packages we have used thus far, including:
<ul>
<li><code>ggplot2</code> for data visualization</li>
<li><code>dplyr</code> for data wrangling</li>
<li>As well as the more advanced <code>purrr</code>, <code>tidyr</code>, <code>readr</code>, <code>tibble</code>, <code>stringr</code>, and <code>forcats</code> packages</li>
</ul></li>
<li>The <code>skimr</code> <span class="citation">(<a href="#ref-R-skimr" role="doc-biblioref"><strong>R-skimr?</strong></a>)</span> package, which provides a simple-to-use function to quickly compute a wide array of commonly-used summary statistics. </li>
</ol>
<p>If needed, read Section <a href="getting-started.html#packages">3.6</a> for information on how to install and load R packages. We will also load the <code>atlas</code> dataset.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="regression.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb52-2"><a href="regression.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb52-3"><a href="regression.html#cb52-3" aria-hidden="true" tabindex="-1"></a>atlas <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">gzcon</span>(<span class="fu">url</span>(<span class="st">&quot;https://raw.githubusercontent.com/jrm87/ECO3253_repo/master/data/atlas.rds&quot;</span>)))</span></code></pre></div>
<hr />
</div>
<div id="model1" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> One numerical explanatory variable<a href="regression.html#model1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s say you want to explore what correlates with economic mobility for children of poor parents (those at percentile 25 of the parental income distribution). To try to keep things simple, you want to understand if neighborhoods that have more jobs, tend to provide more or less economic mobility for this population. We will try to keep things simple for now and explain the differences in mobility with the average job growth rate between 2004 and 2013 (a rough measurement of how much jobs grow in that area) correlates with economic mobility for children from poor parents</p>
<p>We’ll achieve ways to address these questions by modeling the relationship between these two variables with a particular kind of linear regression called <em>simple linear regression</em>. Simple linear regression is the most basic form of linear regression. With it we have</p>
<ol style="list-style-type: decimal">
<li>A numerical outcome variable <span class="math inline">\(y\)</span>. In this case, economic mobility for children of parents in the percentile 25.</li>
<li>A single numerical explanatory variable <span class="math inline">\(x\)</span>. In this case, the average annual job growth rate between 2004 and 2013 for that neighborhood.</li>
</ol>
<div id="model1EDA" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Exploratory data analysis<a href="regression.html#model1EDA" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A crucial step before doing any kind of modeling or analysis is performing an <em>exploratory data analysis</em>, or EDA, of all our data. Exploratory data analysis can give you a sense of the distribution of the data and whether there are outliers and/or missing values. Most importantly, it can inform how to build your model. There are many approaches to exploratory data analysis; here are three:</p>
<ol style="list-style-type: decimal">
<li>Most fundamentally: just looking at the raw values, in a spreadsheet for example. While this may seem trivial, many people ignore this crucial step!</li>
<li>Computing summary statistics like means, medians, and standard deviations.</li>
<li>Creating data visualizations.</li>
</ol>
<p>Let’s load the <code>atlas</code> data, <code>select</code> only a subset of the variables (including the ‘names’, which are the codes of tract, country and state), and look at the raw values. Recall you can look at the raw values by running <code>View()</code> in the console in RStudio to pop-up the spreadsheet viewer with the data frame of interest as the argument to <code>View()</code>. Here, however, we present only a snapshot of five randomly chosen rows:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="regression.html#cb53-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="ot">&lt;-</span> atlas <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="regression.html#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tract, county, state, kfr_pooled_p25, ann_avg_job_growth_2004_2013)</span></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="regression.html#cb54-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="regression.html#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">5</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-61">Table 6.1: </span>Random sample of 5 neighborhoods
</caption>
<thead>
<tr>
<th style="text-align:right;">
tract
</th>
<th style="text-align:right;">
county
</th>
<th style="text-align:right;">
state
</th>
<th style="text-align:right;">
kfr_pooled_p25
</th>
<th style="text-align:right;">
ann_avg_job_growth_2004_2013
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
90200
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
28016
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
<tr>
<td style="text-align:right;">
602004
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
30825
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:right;">
16000
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
48741
</td>
<td style="text-align:right;">
0.030
</td>
</tr>
<tr>
<td style="text-align:right;">
40101
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
35800
</td>
<td style="text-align:right;">
-0.024
</td>
</tr>
<tr>
<td style="text-align:right;">
211400
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
34588
</td>
<td style="text-align:right;">
0.013
</td>
</tr>
</tbody>
</table>
<p>You can see the full description of each variable in the Section on Data Description for Project 1 and the bulk of <a href="lec1_geomobility.html#lec1_geomobility">Lecture 1 on the Geography of Economic Mobility</a>, but let’s summarize what each variable represents:</p>
<ol style="list-style-type: decimal">
<li><code>tract</code>: FIPS code for the tract</li>
<li><code>country</code>: FIPS code for the county</li>
<li><code>state</code>: FIPS code for the state</li>
<li><code>kfr_pooled_p25</code>: Numerical variable of the average income that children that grew up in that neighborhood from parents in the percentile 25th receive when adults.</li>
<li><code>ann_avg_job_growth_2004_2013</code>: Numerical variable of average job growth between 2004 and 2013. Notice that the numbers on job growth need to be multiplied by 100 to get percentages. That is, 0 is 0\%, while 1 would be 100\%.</li>
</ol>
<p>An alternative way to look at the raw data values is by choosing a random sample of the rows in <code>atlas_mob_jobs</code> by piping it into the <code>sample_n()</code> function from the <code>dplyr</code> package. Here we set the <code>size</code> argument to be <code>5</code>, indicating that we want a random sample of 5 rows. We display the results in Table <a href="regression.html#tab:five-random-courses">6.2</a>. Note that due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="regression.html#cb55-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="regression.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">5</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:five-random-courses">Table 6.2: </span>A random sample of 5 neighborhoods
</caption>
<thead>
<tr>
<th style="text-align:right;">
tract
</th>
<th style="text-align:right;">
county
</th>
<th style="text-align:right;">
state
</th>
<th style="text-align:right;">
kfr_pooled_p25
</th>
<th style="text-align:right;">
ann_avg_job_growth_2004_2013
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9200
</td>
<td style="text-align:right;">
157
</td>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
34943
</td>
<td style="text-align:right;">
-0.090
</td>
</tr>
<tr>
<td style="text-align:right;">
2605
</td>
<td style="text-align:right;">
99
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
32270
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:right;">
15100
</td>
<td style="text-align:right;">
71
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
29352
</td>
<td style="text-align:right;">
-0.102
</td>
</tr>
<tr>
<td style="text-align:right;">
950700
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
33694
</td>
<td style="text-align:right;">
0.024
</td>
</tr>
<tr>
<td style="text-align:right;">
52902
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
33021
</td>
<td style="text-align:right;">
-0.017
</td>
</tr>
</tbody>
</table>
<p>Now that we’ve looked at the raw values in our <code>atlas_mob_jobs</code> data frame and got a preliminary sense of the data, let’s move on to the next common step in an exploratory data analysis: computing summary statistics. Let’s start by computing the mean and median of our numerical outcome variable <code>kfr_pooled_p25</code> and our numerical explanatory variable on ob growth denoted as <code>ann_avg_job_growth_2004_2013</code>. We’ll do this by using the <code>summarize()</code> function from <code>dplyr</code> along with the <code>mean()</code> and <code>median()</code> summary functions, in a function that although we did not cover, is fairly intuitive: <code>summarize</code>. It will take some data, and summarize it according to what you ask.</p>
<pre><code>## # A tibble: 1 x 4
##   mean_ann_avg_job_gro~ mean_kfr_pooled_~ median_ann_avg_job_~ median_kfr_poole~
##                   &lt;dbl&gt;             &lt;dbl&gt;                &lt;dbl&gt;             &lt;dbl&gt;
## 1                0.0153            34443.              0.00850            33733.</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="regression.html#cb57-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="regression.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_ann_avg_job_growth_2004_2013 =</span> <span class="fu">mean</span>(ann_avg_job_growth_2004_2013, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb57-3"><a href="regression.html#cb57-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_kfr_pooled_p25 =</span> <span class="fu">mean</span>(kfr_pooled_p25, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb57-4"><a href="regression.html#cb57-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_ann_avg_job_growth_2004_2013 =</span> <span class="fu">median</span>(ann_avg_job_growth_2004_2013, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb57-5"><a href="regression.html#cb57-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_kfr_pooled_p25 =</span> <span class="fu">median</span>(kfr_pooled_p25, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<p>However, what if we want other summary statistics as well, such as the standard deviation (a measure of spread), the minimum and maximum values, and various percentiles? Typing out all these summary statistic functions in <code>summarize()</code> would be long and tedious. Instead, let’s use the convenient <code>skim()</code> function from the <code>skimr</code> package. This function takes in a data frame, “skims” it, and returns commonly used summary statistics. Let’s take our <code>atlas_mob_jobs</code> data frame, <code>select()</code> only the outcome and explanatory variables mobility <code>kfr_pooled_p25</code> and job growth <code>ann_avg_job_growth_2004_2013</code>, and pipe them into the <code>skim()</code> function:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="regression.html#cb58-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="regression.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(kfr_pooled_p25, ann_avg_job_growth_2004_2013) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="regression.html#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<pre><code>Skim summary statistics
 n obs: 73278 
 n variables: 2 
── Variable type:numeric ───────────────────────────────────────────────────────
 variable missing complete   n mean   sd   p0  p25  p50 p75 p100
  kfr_pooled_p25                    1267         0.983 34443.     8169.      0     28973      33733.      39167.     105732.
    ann_avg_job_growth_2004_2013      2614         0.964     0.0153    0.0762 -0.607    -0.0189     0.00850     0.0410      1.34  </code></pre>
<p>(Note that for formatting purposes, the inline histogram that is usually printed with <code>skim()</code> has been removed. This can be done by running <code>skim_with(numeric = list(hist = NULL))</code> prior to using the <code>skim()</code> function as well.)</p>
<p>For our two numerical variables mobility <code>kfr_pooled_p25</code> and job growth <code>ann_avg_job_growth_2004_2013</code> it returns:</p>
<ul>
<li><code>missing</code>: the number of missing values</li>
<li><code>complete</code>: the number of non-missing or complete values</li>
<li><code>n</code>: the total number of values</li>
<li><code>mean</code>: the average</li>
<li><code>sd</code>: the standard deviation</li>
<li><code>p0</code>: the 0<sup>th</sup> percentile: the value at which 0% of observations are smaller than it (the <em>minimum</em> value)</li>
<li><code>p25</code>: the 25<sup>th</sup> percentile: the value at which 25% of observations are smaller than it (the <em>1<sup>st</sup> quartile</em>)</li>
<li><code>p50</code>: the 50<sup>th</sup> percentile: the value at which 50% of observations are smaller than it (the <em>2<sup>nd</sup></em> quartile and more commonly called the <em>median</em>)</li>
<li><code>p75</code>: the 75<sup>th</sup> percentile: the value at which 75% of observations are smaller than it (the <em>3<sup>rd</sup> quartile</em>)</li>
<li><code>p100</code>: the 100<sup>th</sup> percentile: the value at which 100% of observations are smaller than it (the <em>maximum</em> value)</li>
</ul>
<p>Looking at this output, we get an idea of how the values of both variables distribute. For example, the mean mobility was $ 34,443 whereas the mean job growth was 0.0153 or 1.53%. Furthermore, the middle 50% of mobility were between $28,973 and $39,167 (the first and third quartiles) whereas the middle 50% of job growth were between -0.0189 (-1.89%) and 0.0410 (+4.10%).</p>
<p>The <code>skim()</code> function only returns what are known as <em>univariate</em> summary statistics: functions that take a single variable and return some numerical summary of that variable. However, there also exist <em>bivariate</em> summary statistics: functions that take in two variables and return some summary of those two variables. In particular, when the two variables are numerical, we can compute the <em>correlation coefficient</em>. Generally speaking, <em>coefficients</em> are quantitative expressions of a specific phenomenon. A <em>correlation coefficient</em> is a quantitative expression of the <em>strength of the linear relationship between two numerical variables</em>. Its value ranges between -1 and 1 where:</p>
<ul>
<li>-1 indicates a perfect <em>negative relationship</em>: As the value of one variable goes up, the value of the other variable tends to go down following along a straight line.</li>
<li>0 indicates no relationship: The values of both variables go up/down independently of each other.</li>
<li>+1 indicates a perfect <em>positive relationship</em>: As the value of one variable goes up, the value of the other variable tends to go up as well in a linear fashion.</li>
</ul>
<p>Figure <a href="regression.html#fig:correlation1">6.1</a> gives examples of different correlation coefficient values for hypothetical numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. We see that while for a correlation coefficient of -0.75 there is still a negative relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, it is not as strong as the negative relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> when the correlation coefficient is -1.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:correlation1"></span>
<img src="_main_files/figure-html/correlation1-1.png" alt="Different correlation coefficients" width="\textwidth" />
<p class="caption">
Figure 6.1: Different correlation coefficients
</p>
</div>
<p>The correlation coefficient is computed using the <code>cor()</code> function, where the inputs to the function are the two numerical variables for which we want to quantify the strength of the linear relationship. Note, however, that because the dataset has missing values for some neighborhoods, if you run <code>cor()</code> without the option <code>use = "pairwise.complete.obs"</code>, you will get <code>NA</code> - which is a missing value. See that we add this option below:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="regression.html#cb60-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="regression.html#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(kfr_pooled_p25, ann_avg_job_growth_2004_2013, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1      0.0716</code></pre>
<p>You can also use the <code>cor()</code> function directly instead of using it inside <code>summarise</code>, but you will need to use the <code>$</code> syntax to access the specific variables within a data frame (See Subsection <a href="getting-started.html#exploredataframes">3.7.4</a>):</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="regression.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> atlas_mob_jobs<span class="sc">$</span>ann_avg_job_growth_2004_2013, <span class="at">y =</span> atlas_mob_jobs<span class="sc">$</span>kfr_pooled_p25, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.0716</code></pre>
<p>In our case, the correlation coefficient of NA indicates that the relationship between mobility and job growth is “weakly positive” There is a certain amount of subjectivity in interpreting correlation coefficients, especially those that aren’t close to -1, 0, and 1. For help developing such intuition and more discussion on the correlation coefficient see Subsection <a href="regression.html#correlationcoefficient">6.2.1</a> below.</p>
<p>Let’s now proceed by visualizing this data. Since both the <code>kfr_pooled_p25</code> and <code>ann_avg_job_growth_2004_2013</code> variables are numerical, a scatterplot is an appropriate graph to visualize this data. Let’s do this using <code>geom_point()</code> and set informative axes labels and title and display the result in Figure <a href="regression.html#fig:numxplot1">6.2</a>.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="regression.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atlas_mob_jobs, <span class="fu">aes</span>(<span class="at">x =</span> ann_avg_job_growth_2004_2013, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb64-2"><a href="regression.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb64-3"><a href="regression.html#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Job Growth Rate 2004-2013&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Mobility for Children of Parents in P25&quot;</span>, </span>
<span id="cb64-4"><a href="regression.html#cb64-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Relationship of mobility and job growth&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:numxplot1"></span>
<img src="_main_files/figure-html/numxplot1-1.png" alt="Economic mobility for children of parents at percentile 25 across the US" width="\textwidth" />
<p class="caption">
Figure 6.2: Economic mobility for children of parents at percentile 25 across the US
</p>
</div>
<p>Observe the following:</p>
<ol style="list-style-type: decimal">
<li>Most average job growth rates lie between -0.25 (-25%) and 0.25 (+25%).</li>
<li>Most mobility outcomes lie between $18,000 and $50,000.</li>
<li>Recall our earlier computation of the correlation coefficient, which describes the strength of the linear relationship between two numerical variables. Looking at Figure <a href="regression.html#fig:numxplot1">6.2</a>, it is not immediately apparent that these two variables are positively related. This is to be expected given the positive, but rather weak (close to 0), correlation coefficient of NA.</li>
</ol>
<p>Going back to scatterplot in Figure <a href="regression.html#fig:numxplot1">6.2</a>, let’s improve on it by adding a “regression line” in Figure <a href="regression.html#fig:numxplot3">6.3</a>. This is easily done by adding a new layer to the <code>ggplot</code> code that created Figure <a href="regression.html#fig:numxplot1">6.2</a>: <code>+ geom_smooth(method = "lm")</code>. A regression line is a “best fitting” line in that of all possible lines you could draw on this plot, it is “best” in terms of some mathematical criteria. There is a formal definition for what “best” means, but we do not need to go into detail here. Suffice to say, this line minimizes errors in the prediction in the sense that the square of the distance between our prediction (the line) and the real data.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="regression.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atlas_mob_jobs, <span class="fu">aes</span>(<span class="at">x =</span> ann_avg_job_growth_2004_2013, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="regression.html#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb65-3"><a href="regression.html#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Job Growth Rate 2004-2013&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Mobility for Children of Parents in P25&quot;</span>, </span>
<span id="cb65-4"><a href="regression.html#cb65-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Relationship of mobility and job growth&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb65-5"><a href="regression.html#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:numxplot3"></span>
<img src="_main_files/figure-html/numxplot3-1.png" alt="Regression line" width="\textwidth" />
<p class="caption">
Figure 6.3: Regression line
</p>
</div>
<p>When viewed on this plot, the regression line is a visual summary of the relationship between two numerical variables, in our case the outcome variable <code>kfr_pooled_p25</code> and the explanatory variable <code>ann_avg_job_growth_2004_2013</code>. The positive slope of the blue line is consistent with our observed correlation coefficient of NA suggesting that there is a positive relationship between <code>kfr_pooled_p25</code> and <code>ann_avg_job_growth_2004_2013</code>. We’ll see later however that while the correlation coefficient is not equal to the slope of this line, they always have the same sign: positive or negative.</p>
<p>You can barely see it. perhaps, but the blue line has some very thin grey bands surrounding it. What are those? These are <em>standard error</em> bands, which can be thought of as error/uncertainty bands. Let’s skip this idea for now and suppress these grey bars by adding the argument <code>se = FALSE</code> to <code>geom_smooth(method = "lm")</code>. We’ll briefly introduce standard errors below, but we can skip that for now.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="regression.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atlas_mob_jobs, <span class="fu">aes</span>(<span class="at">x =</span> ann_avg_job_growth_2004_2013, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb67-2"><a href="regression.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb67-3"><a href="regression.html#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Job Growth Rate 2004-2013&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Mobility for Children of Parents in P25&quot;</span>, </span>
<span id="cb67-4"><a href="regression.html#cb67-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Relationship of mobility and job growth&quot;</span>) <span class="sc">+</span></span>
<span id="cb67-5"><a href="regression.html#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:numxplot4"></span>
<img src="_main_files/figure-html/numxplot4-1.png" alt="Regression line without error bands" width="\textwidth" />
<p class="caption">
Figure 6.4: Regression line without error bands
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC5.1)</strong> Conduct a new exploratory data analysis with the same outcome variable <span class="math inline">\(y\)</span> being <code>kfr_pooled_p25</code> but with <code>poor_share2010</code> as the new explanatory variable <span class="math inline">\(x\)</span>. Remember, this involves three things:</p>
<ol style="list-style-type: lower-alpha">
<li>Looking at the raw values.</li>
<li>Computing summary statistics of the variables of interest.</li>
<li>Creating informative visualizations.</li>
</ol>
<p>What can you say about the relationship between the share of people living under the poverty line in 2010 and mobility measures for children of parents in p25 based on this exploration?</p>
<div class="learncheck">

</div>
</div>
<div id="model1table" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Simple linear regression<a href="regression.html#model1table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You may recall from secondary school / high school algebra, in general, the equation of a line is <span class="math inline">\(y = a + bx\)</span>, which is defined by two coefficients. Recall we defined this earlier as “quantitative expressions of a specific property of a phenomenon.” These two coefficients are:</p>
<ul>
<li>the intercept coefficient <span class="math inline">\(a\)</span>, or the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>, and</li>
<li>the slope coefficient <span class="math inline">\(b\)</span>, or the increase in <span class="math inline">\(y\)</span> for every increase of one in <span class="math inline">\(x\)</span>.</li>
</ul>
<p>However, when defining a line specifically for regression, like the blue regression line in Figure <a href="regression.html#fig:numxplot4">6.4</a>, we use slightly different notation: the equation of the regression line is <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> where</p>
<ul>
<li>the intercept coefficient is <span class="math inline">\(b_0\)</span>, or the value of <span class="math inline">\(\widehat{y}\)</span> when <span class="math inline">\(x=0\)</span>, and</li>
<li>the slope coefficient <span class="math inline">\(b_1\)</span>, or the increase in <span class="math inline">\(\widehat{y}\)</span> for every increase of one in <span class="math inline">\(x\)</span>.</li>
</ul>
<p>Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in regression, which we’ll introduce in the next Subsection <a href="#model1points"><strong>??</strong></a> when we discuss <em>fitted values</em>. For now, let’s ignore the hat and treat the equation of the line as you would from secondary school / high school algebra recognizing the slope and the intercept. We know looking at Figure <a href="regression.html#fig:numxplot4">6.4</a> that the slope coefficient corresponding to <code>ann_avg_job_growth_2004_2013</code> should be positive. Why? Because as <code>ann_avg_job_growth_2004_2013</code> increases, professors tend to roughly have higher teaching evaluation <code>kfr_pooled_p25</code>. However, what are the specific values of the intercept and slope coefficients? Let’s not worry about computing these by hand, but instead let the computer do the work for us. Specifically, let’s use R!</p>
<p>Let’s get the value of the intercept and slope coefficients by outputting something called the <em>linear regression table</em>. We will fit the linear regression model to the <code>data</code> using the <code>lm()</code> function and save this to <code>mob_model</code>. <code>lm</code> stands for “linear model.” When we say “fit”, we are saying find the best fitting line to this data.</p>
<p>The <code>lm()</code> function that “fits” the linear regression model is typically used as <code>lm(y ~ x, data = data_frame_name)</code> where:</p>
<ul>
<li><code>y</code> is the outcome variable, followed by a tilde (<code>~</code>). This is likely the key to the left of “1” on your keyboard. In our case, <code>y</code> is set to <code>kfr_pooled_p25</code>.</li>
<li><code>x</code> is the explanatory variable. In our case, <code>x</code> is set to <code>ann_avg_job_growth_2004_2013</code>. We call the combination <code>y ~ x</code> a <em>model formula</em>.</li>
<li><code>data_frame_name</code> is the name of the data frame that contains the variables <code>y</code> and <code>x</code>. In our case, <code>data_frame_name</code> is the <code>atlas_mob_jobs</code> data frame.</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="regression.html#cb69-1" aria-hidden="true" tabindex="-1"></a>mob_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(kfr_pooled_p25 <span class="sc">~</span> ann_avg_job_growth_2004_2013, <span class="at">data =</span> atlas_mob_jobs)</span>
<span id="cb69-2"><a href="regression.html#cb69-2" aria-hidden="true" tabindex="-1"></a>mob_model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = kfr_pooled_p25 ~ ann_avg_job_growth_2004_2013, data = atlas_mob_jobs)
## 
## Coefficients:
##                  (Intercept)  ann_avg_job_growth_2004_2013  
##                        34276                          7783</code></pre>
<p>This output is telling us that the <code>Intercept</code> coefficient <span class="math inline">\(b_0\)</span> of the regression line is 3.8803, and the slope coefficient for <code>by_avg</code> is 0.0666. Therefore the blue regression line in Figure <a href="regression.html#fig:numxplot4">6.4</a> is</p>
<p><span class="math display">\[\widehat{\text{mobilityp25}} = b_0 + b_{\text{avg job growth}} \cdot\text{avg job growth} = 34276.27 + 7782.82\cdot\text{ avg job growth}\]</span></p>
<p>where</p>
<ul>
<li><p>The intercept coefficient <span class="math inline">\(b_0 = 34276.27\)</span> means for instructors that had a hypothetical average job growth of 0, we would expect them to have on average mobility of $ 34,276.</p></li>
<li><p>Of more interest is the slope coefficient associated with <code>ann_avg_job_growth_2004_2013</code>: <span class="math inline">\(b_{\text{bty avg}} = +7782.82\)</span>. This is a numerical quantity that summarizes the relationship between the outcome and explanatory variables. Note that the sign is positive, suggesting a positive relationship between job growth and mobility, meaning as average job growth goes up, so does the mobility measure. The slope’s precise interpretation is:</p>
<blockquote>
<p>For every increase of 1 unit in <code>ann_avg_job_growth_2004_2013</code>, there is an <em>associated</em> increase of, <em>on average</em>, 7782.82 units of <code>kfr_pooled_p25</code>.</p>
</blockquote></li>
</ul>
<p>A very important point to mention here is that you need to recall that the variable <code>ann_avg_job_growth_2004_2013</code> is coded such that a 1 unit increment is equivalent to increasing the average annual job growth by 100%. Given that changing the average growth rate by 100% is a very large change, perhaps we should choose a smaller change to get a sense of how much the correlation explains mobility. That is, we can interpret the previous set of results by dividing the coefficient on average job growth rate by 100, and saying:</p>
<blockquote>
<p>For every increase of 1% in the average job growth rate <code>ann_avg_job_growth_2004_2013</code>, there is an <em>associated</em> increase of, <em>on average</em>, 77.82 units of <code>mobility</code>.</p>
</blockquote>
<p>Such interpretations need be carefully worded:</p>
<ul>
<li>We only stated that there is an <em>associated</em> increase, and not necessarily a <em>causal</em> increase. For example, perhaps it’s not that job growth directly affects mobility, but instead areas with higher mobility attract firms to locate there, thereby increasing job creation. Avoiding such reasoning can be summarized by the adage “correlation is not necessarily causation.” In other words, just because two variables are correlated, it doesn’t mean one directly causes the other. We discuss these ideas more in Subsection <a href="regression.html#correlation-is-not-causation">6.2.2</a> and in following chapters.<br />
</li>
<li>We say that this associated increase is <em>on average</em> 77.82 dollars of mobility <code>kfr_pooled_p25</code> and not that the associated increase is <em>exactly</em> 77.82 dollars of <code>kfr_pooled_p25</code> across all values of <code>ann_avg_job_growth_2004_2013</code>. This is because the slope is the average increase across all points as shown by the regression line in Figure <a href="regression.html#fig:numxplot4">6.4</a>.</li>
</ul>
<p>Now that we’ve learned how to compute the equation for the blue regression line in Figure <a href="regression.html#fig:numxplot4">6.4</a> and interpreted all its terms, let’s take our modeling one step further. This time after fitting the model using the <code>lm()</code>, let’s get something called the <em>regression table</em> using the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="regression.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb71-2"><a href="regression.html#cb71-2" aria-hidden="true" tabindex="-1"></a>mob_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(kfr_pooled_p25 <span class="sc">~</span> ann_avg_job_growth_2004_2013, <span class="at">data =</span> atlas_mob_jobs)</span>
<span id="cb71-3"><a href="regression.html#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression results:</span></span>
<span id="cb71-4"><a href="regression.html#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mob_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = kfr_pooled_p25 ~ ann_avg_job_growth_2004_2013, data = atlas_mob_jobs)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -35002  -5437   -719   4656  69932 
## 
## Coefficients:
##                              Estimate Std. Error t value            Pr(&gt;|t|)
## (Intercept)                   34276.3       31.2    1097 &lt;0.0000000000000002
## ann_avg_job_growth_2004_2013   7782.8      409.2      19 &lt;0.0000000000000002
##                                 
## (Intercept)                  ***
## ann_avg_job_growth_2004_2013 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8110 on 70230 degrees of freedom
##   (3046 observations deleted due to missingness)
## Multiple R-squared:  0.00512,    Adjusted R-squared:  0.00511 
## F-statistic:  362 on 1 and 70230 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>Note how we took the output of the model fit saved in <code>mob_model</code> and used it as an input to the subsequent <code>summary()</code> function. The raw output of the <code>summary()</code> function above gives lots of information about the regression model that we won’t cover in this introductory course (e.g., Multiple R-squared, F-statistic, etc.). We will only consider the “Coefficients” section of the output. We can print these relevant results only by accessing the <code>coefficients</code> object stored in the summary results.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="regression.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mob_model)<span class="sc">$</span>coefficients</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:numxplot4b">Table 6.3: </span>Linear regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
34276
</td>
<td style="text-align:right;">
31.2
</td>
<td style="text-align:right;">
1097
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
ann_avg_job_growth_2004_2013
</td>
<td style="text-align:right;">
7783
</td>
<td style="text-align:right;">
409.2
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>For now since we are only using regression as an exploratory data analysis tool, we will only focus on the “Estimate” column that contains the estimates of the intercept and slope for the best fit line for our data. The remaining three columns refer to statistical concepts known as standard errors, t-statistics, and p-values. They are all interrelated, but we will briefly only talk about p-values at the end of this Chapter. For now, we can skip that..</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC5.2)</strong> Fit a new simple linear regression using <code>lm(kfr_pooled_p25 ~ poor_share2010, data = atlas_mob_jobs)</code> where <code>poor_share2010</code> is the new explanatory variable <span class="math inline">\(x\)</span>. Get information about the “best-fitting” line from the regression table by applying the <code>summary()</code> function. How do the regression results match up with the results from your exploratory data analysis above?</p>
<div class="learncheck">

</div>
<p>Investigating the residuals of these linear regressions is usually a good idea, but I will leave that for your Econometric classes. If you want to see how to explore the residuals in R, you can look <a href="https://nustat.github.io/intro-stat-ds/5-regression.html#model1points">here</a>.</p>
<hr />
</div>
</div>
<div id="related-topics" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Related topics<a href="regression.html#related-topics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="correlationcoefficient" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Correlation coefficient<a href="regression.html#correlationcoefficient" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s re-plot Figure <a href="regression.html#fig:correlation1">6.1</a>, but now consider a broader range of correlation coefficient values in Figure <a href="regression.html#fig:correlation2">6.5</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:correlation2"></span>
<img src="_main_files/figure-html/correlation2-1.png" alt="Different Correlation Coefficients" width="\textwidth" />
<p class="caption">
Figure 6.5: Different Correlation Coefficients
</p>
</div>
<p>As we suggested in Subsection <a href="regression.html#model1EDA">6.1.1</a>, interpreting coefficients that are not close to the extreme values of -1 and 1 can be subjective. To help develop your sense of correlation coefficients, we suggest you play the following 80’s-style video game called “Guess the correlation” at <a href="http://guessthecorrelation.com/" class="uri">http://guessthecorrelation.com/</a>.</p>
</div>
<div id="correlation-is-not-causation" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Correlation is not necessarily causation<a href="regression.html#correlation-is-not-causation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You’ll note throughout this chapter we’ve been very cautious in making statements of the “associated effect” of explanatory variables on the outcome variables, for example our statement from Subsection <a href="regression.html#model1table">6.1.2</a> that “for every increase of 1 unit in <code>ann_avg_job_growth_2004_2013</code>, there is an <em>associated</em> increase of, <em>on average</em>, 7782.823 units of <code>kfr_pooled_p25</code>.” We say this because we are careful not to make <em>causal</em> statements. So while average job growth rate <code>ann_avg_job_growth_2004_2013</code> is positively correlated with teaching <code>kfr_pooled_p25</code>, it does not imply that it directly cause mobility to increase.</p>
<p>For example, let’s say a neighbrhood has their <code>ann_avg_job_growth_2004_2013</code> increase, but only after taking steps to try to boost public investment in the area. Does this mean that they will suddenly be a better neighborhood for kids of low income parents? Maybe?</p>
<p>Here is another example, a not-so-great medical doctor goes through their medical records and finds that patients who slept with their shoes on tended to wake up more with headaches. So this doctor declares “Sleeping with shoes on cause headaches!”</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:moderndive-figure-causal-graph-2"></span>
<img src="images/flowcharts/flowchart.010-cropped.png" alt="Does sleeping with shoes on cause headaches?" width="\textwidth" />
<p class="caption">
Figure 6.6: Does sleeping with shoes on cause headaches?
</p>
</div>
<p>However as some of you might have guessed, if someone is sleeping with their shoes on it’s probably because they are intoxicated. Furthermore, drinking more tends to cause more hangovers, and hence more headaches.</p>
<p>In this instance, alcohol is what’s known as a <em>confounding/lurking</em> variable. It “lurks” behind the scenes, confounding or making less apparent, the causal effect (if any) of “sleeping with shoes on” with waking up with a headache. We can summarize this notion in Figure <a href="regression.html#fig:moderndive-figure-causal-graph">6.7</a> with a <em>causal graph</em> where:</p>
<ul>
<li>Y: Is an <em>outcome</em> variable, here “waking up with a headache.”</li>
<li>X: Is a <em>treatment</em> variable whose causal effect we are interested in, here “sleeping with shoes on.”</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:moderndive-figure-causal-graph"></span>
<img src="images/flowcharts/flowchart.009-cropped.png" alt="Causal graph." width="\textwidth" />
<p class="caption">
Figure 6.7: Causal graph.
</p>
</div>
<p>So for example, many such studies use regression modeling where the outcome variable is set to Y and the explanatory/predictor variable is X, much as you’ve started learning how to do in this chapter. However, Figure <a href="regression.html#fig:moderndive-figure-causal-graph">6.7</a> also includes a third variable with arrows pointing at both X and Y.</p>
<ul>
<li>Z: Is a <em>confounding</em> variable that affects both X &amp; Y, thus “confounding” their relationship.</li>
</ul>
<p>So as we said, alcohol will both cause people to be more likely to sleep with their shoes on as well as more likely to wake up with a headache. Thus when evaluating what causes one to wake up with a headache, its hard to tease out the effect of sleeping with shoes on versus just the alcohol. Thus our model needs to also use Z as an explanatory/predictor variable as well, in other words our doctor needs to take into account who had been drinking the night before. We’ll start covering multiple regression models that allows us to incorporate more than one variable in the next chapter.</p>
<p>Establishing causation is a tricky problem and frequently takes either carefully designed experiments or methods to control for the effects of potential confounding variables. Both these approaches attempt either to remove all confounding variables or take them into account as best they can, and only focus on the behavior of an outcome variable in the presence of the levels of the other variable(s). Be careful as you read studies to make sure that the writers aren’t falling into this fallacy of correlation implying causation. If you spot one, you may want to send them a link to <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a>.</p>
<hr />
</div>
</div>
<div id="model3" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Two numerical explanatory variables<a href="regression.html#model3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s first consider a <em>multiple regression</em> model with two numerical explanatory variables. We will continue with our previous example coming from the <code>atlas</code> data.</p>
<p>In this section, we’ll fit a regression model where we have</p>
<ol style="list-style-type: decimal">
<li>A numerical outcome variable <span class="math inline">\(y\)</span>, the mobility measure for children of parents in the percentile 25th.</li>
<li>Two explanatory variables:
<ol style="list-style-type: decimal">
<li>One numerical explanatory variable <span class="math inline">\(x_1\)</span>, average job growth rate between 2003 and 2014.</li>
<li>Another numerical explanatory variable <span class="math inline">\(x_2\)</span>, the percentage of the population below the poverty line in 2010.</li>
</ol></li>
</ol>
<div id="model3EDA" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Exploratory data analysis<a href="regression.html#model3EDA" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s do something similar to what we did before, but include the variable of the share of the population below the poverty line in 2010 <code>poor_share2010</code> in the data that we keep track off, and call it <code>atlas_mob_jobs_poor</code>.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="regression.html#cb74-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs_poor <span class="ot">&lt;-</span> atlas <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="regression.html#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tract, county, state, kfr_pooled_p25, ann_avg_job_growth_2004_2013, poor_share2010)</span></code></pre></div>
<p>Recall the three common steps in an exploratory data analysis we saw in Subsection <a href="regression.html#model1EDA">6.1.1</a>:</p>
<ol style="list-style-type: decimal">
<li>Looking at the raw data values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>Let us know skim the data with the <code>skim()</code> function:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="regression.html#cb75-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs_poor <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="regression.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(kfr_pooled_p25, ann_avg_job_growth_2004_2013, poor_share2010) <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="regression.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<pre><code>Skim summary statistics
 n obs: 73278 
 n variables: 2 
── Variable type:numeric ───────────────────────────────────────────────────────
 variable missing complete   n mean   sd   p0  p25  p50 p75 p100
  kfr_pooled_p25                    1267         0.983 34443.     8169.      0     28973      33733.      39167.     105732.
    ann_avg_job_growth_2004_2013      2614         0.964     0.0153    0.0762 -0.607    -0.0189     0.00850     0.0410      1.34  
   poor_share2010                     345         0.995     0.151     0.127   0         0.0591     0.116       0.205       1</code></pre>
<p>Observe the summary statistics for the min and max of the variable <code>poor_share2010</code> are 0 and 1, respectively. This should be a <strong>flag</strong> for you that the share is once more measured as 0 being 0% and 1 being 100%. Note that the average share of population living below the poverty line in 2010 is 15.1%, and that 25% of neighborhoods have a poverty share of 5.91% or less, while 75% of neighborhoods had a poverty share of 20.5% or less.</p>
<p>Since our outcome variable <code>kfr_pooled_p25</code> and the explanatory variables <code>ann_avg_job_growth_2004_2013</code> and <code>poor_share2010</code> are numerical, we can compute the correlation coefficient between the different possible pairs of these variables. First, we can run the <code>cor()</code> command as seen in Subsection <a href="regression.html#model1EDA">6.1.1</a> twice, once for each explanatory variable:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="regression.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(atlas_mob_jobs_poor<span class="sc">$</span>kfr_pooled_p25, atlas_mob_jobs_poor<span class="sc">$</span>ann_avg_job_growth_2004_2013, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span>
<span id="cb77-2"><a href="regression.html#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="regression.html#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(atlas_mob_jobs_poor<span class="sc">$</span>kfr_pooled_p25, atlas_mob_jobs_poor<span class="sc">$</span>poor_share2010, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span></code></pre></div>
<p>Or we can simultaneously compute them by returning a <em>correlation matrix</em> which we display in Table <a href="regression.html#tab:model3-correlation">6.4</a>. We can read off the correlation coefficient for any pair of variables by looking them up in the appropriate row/column combination.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="regression.html#cb78-1" aria-hidden="true" tabindex="-1"></a>atlas_mob_jobs_poor <span class="sc">%&gt;%</span></span>
<span id="cb78-2"><a href="regression.html#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(kfr_pooled_p25, ann_avg_job_growth_2004_2013, poor_share2010) <span class="sc">%&gt;%</span> </span>
<span id="cb78-3"><a href="regression.html#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:model3-correlation">Table 6.4: </span>Correlation coefficients between mobility, job growth and poverty rate.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
kfr_pooled_p25
</th>
<th style="text-align:right;">
ann_avg_job_growth_2004_2013
</th>
<th style="text-align:right;">
poor_share2010
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
kfr_pooled_p25
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.072
</td>
<td style="text-align:right;">
-0.544
</td>
</tr>
<tr>
<td style="text-align:left;">
ann_avg_job_growth_2004_2013
</td>
<td style="text-align:right;">
0.072
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.063
</td>
</tr>
<tr>
<td style="text-align:left;">
poor_share2010
</td>
<td style="text-align:right;">
-0.544
</td>
<td style="text-align:right;">
-0.063
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
</tbody>
</table>
<p>For example, the correlation coefficient of:</p>
<ol style="list-style-type: decimal">
<li><code>kfr_pooled_p25</code> with itself is 1 as we would expect based on the definition of the correlation coefficient.</li>
<li><code>kfr_pooled_p25</code> with <code>ann_avg_job_growth_2004_2013</code> is 0.072. This indicates a very weak positive linear relationship.</li>
<li><code>kfr_pooled_p25</code> with <code>poor_share2010</code> is -0.544. This is suggestive of a strong negative linear relationship. At least, much stronger than the one between <code>kfr_pooled_p25</code> and <code>ann_avg_job_growth_2004_2013</code>.</li>
<li>As an added bonus, we can read off the correlation coefficient between the two explanatory variables of <code>ann_avg_job_growth_2004_2013</code> and <code>poor_share2010</code> as -0.063.</li>
</ol>
<p>Let’s visualize the relationship of the outcome variable with each of the two explanatory variables in two separate plots in Figure <a href="regression.html#fig:2numxplot1">6.8</a>.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="regression.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atlas_mob_jobs_poor, <span class="fu">aes</span>(<span class="at">x =</span> ann_avg_job_growth_2004_2013, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb79-2"><a href="regression.html#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb79-3"><a href="regression.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Average Job Growth 2003-2014&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Mobility for Children of Parents in P25 (in $)&quot;</span>, </span>
<span id="cb79-4"><a href="regression.html#cb79-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Mobility and job growth&quot;</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="regression.html#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb79-6"><a href="regression.html#cb79-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb79-7"><a href="regression.html#cb79-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atlas_mob_jobs_poor, <span class="fu">aes</span>(<span class="at">x =</span> poor_share2010, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb79-8"><a href="regression.html#cb79-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb79-9"><a href="regression.html#cb79-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proverty Share in 2010&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Mobility for Children of Parents in P25 (in $)&quot;</span>, </span>
<span id="cb79-10"><a href="regression.html#cb79-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Mobility and poverty share&quot;</span>) <span class="sc">+</span></span>
<span id="cb79-11"><a href="regression.html#cb79-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:2numxplot1"></span>
<img src="_main_files/figure-html/2numxplot1-1.png" alt="Relationship between mobility and job growth/poverty share." width="\textwidth" />
<p class="caption">
Figure 6.8: Relationship between mobility and job growth/poverty share.
</p>
</div>
<p>Observe there is a weak positive relationship between mobility and job growth: as job growth increases so also does mobility but in a fairly flat rate. This is consistent with the weak positive correlation coefficient of 0.072 we computed earlier. In the case of poverty share, the strong negative relationship appear here, which depicts the -0.544 correlation coefficient that we estimated above.</p>
<p>However, the two plots in Figure <a href="regression.html#fig:2numxplot1">6.8</a> only focus on the relationship of the outcome variable with each of the two explanatory variables <em>separately</em>. To visualize the <em>joint</em> relationship of all three variables simultaneously, we need a 3-dimensional (3D) scatterplot as seen in Figure <a href="regression.html#fig:3D-scatterplot">6.9</a>. Because there are many datapoints in the <code>atlas</code> data, I subset this to data for the state of North Carolina (<code>state==37</code>). These points in the <code>atlas_mob_jobs_poor</code> data frame are marked with a blue point where</p>
<ol style="list-style-type: decimal">
<li>The numerical outcome variable <span class="math inline">\(y\)</span> <code>kfr_pooled_p25</code> is on the vertical axis</li>
<li>The two numerical explanatory variables, <span class="math inline">\(x_1\)</span> <code>poor_share2010</code> and <span class="math inline">\(x_2\)</span> <code>ann_avg_job_growth_2004_2013</code>, are on the two axes that form the bottom plane.</li>
</ol>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3D-scatterplot"></span>
<img src="_main_files/figure-html/3D-scatterplot-1.png" alt="3D scatterplot and regression plane." width="90%" />
<p class="caption">
Figure 6.9: 3D scatterplot and regression plane.
</p>
</div>
<p>Furthermore, we also include the <em>regression plane</em>. Recall from above that regression lines are “best-fitting” in that of all possible lines we can draw through a cloud of points, the regression line minimizes the <em>sum of squared residuals</em>. This concept also extends to models with two numerical explanatory variables. The difference is instead of a “best-fitting” line, we now have a “best-fitting” plane that similarly minimizes the sum of squared residuals. Head to <a href="https://beta.rstudioconnect.com/connect/#/apps/3214/">here</a> to open an interactive version of similar plane (using different data) in your browser.</p>
</div>
<div id="model3table" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Regression plane<a href="regression.html#model3table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now fit a regression model and get the regression table corresponding to the regression plane in Figure <a href="regression.html#fig:3D-scatterplot">6.9</a>. We’ll consider a model fit with a formula of the form <code>y ~ x1 + x2</code>, where <code>x1</code> and <code>x2</code> represent our two explanatory variables <code>ann_avg_job_growth_2004_2013</code> and <code>poor_share2010</code>.</p>
<p>Just like we did in Chapter <a href="regression.html#regression">6</a>, let’s get the regression table for this model using our two-step process and display the results in Table <a href="regression.html#tab:model3-table-output">6.5</a>.</p>
<ol style="list-style-type: decimal">
<li>We first “fit” the linear regression model using the <code>lm(y ~ x1 + x2, data)</code> function and save it in <code>mob_model2</code>.</li>
<li>We get the regression table by applying the <code>summary()</code> function to <code>mob_model2</code>.</li>
</ol>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="regression.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb81-2"><a href="regression.html#cb81-2" aria-hidden="true" tabindex="-1"></a>mob_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kfr_pooled_p25 <span class="sc">~</span> ann_avg_job_growth_2004_2013 <span class="sc">+</span> poor_share2010, <span class="at">data =</span> atlas_mob_jobs_poor)</span>
<span id="cb81-3"><a href="regression.html#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression table:</span></span>
<span id="cb81-4"><a href="regression.html#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mob_model2)<span class="sc">$</span>coefficients</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:model3-table-output">Table 6.5: </span>Multiple regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
39714
</td>
<td style="text-align:right;">
41.4
</td>
<td style="text-align:right;">
959.1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
ann_avg_job_growth_2004_2013
</td>
<td style="text-align:right;">
3684
</td>
<td style="text-align:right;">
345.4
</td>
<td style="text-align:right;">
10.7
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
poor_share2010
</td>
<td style="text-align:right;">
-36371
</td>
<td style="text-align:right;">
214.1
</td>
<td style="text-align:right;">
-169.8
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Let’s interpret the three values in the <code>Estimate</code> column. First, the <code>Intercept</code> value is -$39,714. This intercept represents the mobility for children of parents in p25 in neighborhoods in which <code>ann_avg_job_growth_2004_2013</code> is 0% and <code>poor_share2010</code> of 0%. In our data however, the intercept has limited practical interpretation since no neighborhood had <code>ann_avg_job_growth_2004_2013</code> or <code>poor_share2010</code> values of 0%. Rather, the intercept is used to situate the regression plane in 3D space.</p>
<p>Second, the <code>ann_avg_job_growth_2004_2013</code> value is $3,684. Taking into account all the other explanatory variables in our model, if you increase job growth in a neighborhood from 0% to 100% (<code>ann_avg_job_growth_2004_2013</code> from 0 to 1 unit), there is an associated increase of on average $3,684 in economic mobility for p25. Notice once more, that this is <strong>equivalent</strong> to saying that increasing job growth by 1% has an associated average increase of mobility of $36.84 - which definitely seems like a small amount. Just as we did in Subsection <a href="regression.html#model1table">6.1.2</a>, we are cautious to <em>not</em> imply causality as we saw in Subsection <a href="regression.html#correlation-is-not-causation">6.2.2</a> that “correlation is not necessarily causation.” We do this merely stating there was an <em>associated</em> increase.</p>
<p>Furthermore, we preface our interpretation with the statement “taking into account all the other explanatory variables in our model.” Here, by all other explanatory variables we mean <code>poor_share2010</code>. We do this to emphasize that we are now jointly interpreting the associated effect of multiple explanatory variables in the same model at the same time.</p>
<p>Third, <code>poor_share2010</code> = -$36,371. Taking into account all the other explanatory variables in our model, for every increase of one unit in the variable <code>poor_share2010</code>, in other words decreasing the share poor in a neighborhood from 0% to 100%, there is an associated decrease of on average $36,371 in mobility. Once more, this is equivalent to saying that a reduction of 1% in the share poor is associated with an increase of $363.71 in economic mobility.</p>
<p>Putting these results together, the equation of the regression plane that gives us fitted values <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{mobility}}\)</span> is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} &amp;= b_0 + b_1 \cdot x_1 +  b_2 \cdot x_2\\
\widehat{\text{mobility}} &amp;= b_0 + b_{\text{avg job growth}} \cdot \text{avg job growth} + b_{\text{pov rate}} \cdot \text{pov rate}\\
&amp;= 39714 + 3684 \cdot\text{avg job growth} - 36371 \cdot\text{pov rate}
\end{aligned}
\]</span></p>
<p>Recall in the right-hand plot of Figure <a href="regression.html#fig:2numxplot1">6.8</a> that when plotting the relationship between <code>kfr_pooled_p25</code> and <code>poor_share2010</code> in isolation, there appeared to be a <em>positive</em> relationship of. In the last discussed multiple regression however, when <em>jointly</em> modeling the relationship between <code>kfr_pooled_p25</code>, <code>ann_avg_job_growth_2004_2013</code>, and <code>poor_share2010</code>, there appears to be a <em>weaker</em> positive relationship of <code>kfr_pooled_p25</code> and <code>ann_avg_job_growth_2004_2013</code> as evidenced by the slope for <code>ann_avg_job_growth_2004_2013</code> of $3,684 versus the initial $7,783.</p>
</div>
</div>
<div id="how-to-read-p-values" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> How to read p-values<a href="regression.html#how-to-read-p-values" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that you know what the <strong>coefficients</strong> in a regression table mean, let’s briefly discuss now how to asses if the relationship you estimated (the coefficients) estimated with sufficient precision or not. Let’s recap our latest regression table. We had this:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="regression.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mob_model2)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                              Estimate Std. Error t value
## (Intercept)                     39714       41.4   959.1
## ann_avg_job_growth_2004_2013     3684      345.4    10.7
## poor_share2010                 -36371      214.1  -169.8
##                                                    Pr(&gt;|t|)
## (Intercept)                  0.0000000000000000000000000000
## ann_avg_job_growth_2004_2013 0.0000000000000000000000000152
## poor_share2010               0.0000000000000000000000000000</code></pre>
<p>We will now focus on the last column of these tables - the one that says <strong>Pr(&gt;|t|)</strong>. These numbers are called <strong>p-values</strong>. This is a big topic and I will not do it justice. In fact, I will be very loose in this explanation as this is not a course in statistics, but I do want to give you the intuition for how to read it. If you want to dig more, please see <a href="https://nustat.github.io/intro-stat-ds/9-sampling.html">here</a> and <a href="https://nustat.github.io/intro-stat-ds/11-pvalues.html">here</a>.</p>
<p>In essence, when we run a regression like the one above, we usually have at hand a sample of observations out of a universe. For example, in the <code>atlas</code> instance, we do not have information on all the neighborhoods in the US, although we do have most of them in the data. But that means that we could have ended with a different set of observations (or neighborhoods) in an alternative world that is slightly different from the one we actually see.</p>
<p>To assess how much of an issue this is, we use p-values. I will not get into any details of how you can calculate p-values, but the idea is fairly simple: a p-value is the probability that you would observe data that is as extreme as the data you do if, in fact, the true slope (or coefficient) was zero.</p>
<p>Put another way, if we imagine that there is absolutely <strong>no real</strong> relationship between our variable(s) <span class="math inline">\(x\)</span> and our outcome <span class="math inline">\(y\)</span>, how often would we find data that looks like this or even more extreme in the apparent relationship? The answer is the p-value. Why is that useful? Because if the p-value is sufficiently low it is a very simple way to assess our confidence in the slope we are estimating.</p>
<div class="blackbox">
<div class="center">
<p><strong>Important!</strong></p>
</div>
<p><strong>p-values</strong>: probability that you would observe data that is as extreme as the data you do if, in fact, the true slope (or coefficient) were zero.</p>
<p><strong>interpretation</strong>: rule of thumb is to say that numbers below 0.05 are evidence that the slope is <em>not</em> produced by random chance.</p>
</div>
<div id="an-example" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> An Example<a href="regression.html#an-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s present our latest regression table for the multivariate case once more. We had this table:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="regression.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mob_model2)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                              Estimate Std. Error t value
## (Intercept)                     39714       41.4   959.1
## ann_avg_job_growth_2004_2013     3684      345.4    10.7
## poor_share2010                 -36371      214.1  -169.8
##                                                    Pr(&gt;|t|)
## (Intercept)                  0.0000000000000000000000000000
## ann_avg_job_growth_2004_2013 0.0000000000000000000000000152
## poor_share2010               0.0000000000000000000000000000</code></pre>
<p>Notice that the <strong>p-values</strong> for all three estimates (the intercept, and our coefficients for <code>ann_avg_job_growth_2004_2013</code> and <code>poor_share2010</code>) are 0. What does that mean? Well, that means that it would be very very unlikely that we could get data like the one we have (or more extreme) if the intercept was 0, or if the coefficient of <code>ann_avg_job_growth_2004_2013</code> were 0, or if the coefficient for <code>poor_share2010</code> was 0. That is, in a loose way, we believe these estimates are not just coincidence. If those numbers would be higher than 0.05 we should perhaps trust those numbers a bit less, as there would be a higher probability that they were produced almost by chance.</p>
</div>
</div>
<div id="conclusion-3" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Conclusion<a href="regression.html#conclusion-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="additional-resources-basic-regression" class="section level3 hasAnchor" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> Additional resources<a href="regression.html#additional-resources-basic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As we suggested in Subsection <a href="regression.html#model1EDA">6.1.1</a>, interpreting coefficients that are not close to the extreme values of -1, 0, and 1 can be somewhat subjective. To help develop your sense of correlation coefficients, we suggest you play the following 80’s-style video game called “Guess the correlation” at <a href="http://guessthecorrelation.com/" class="uri">http://guessthecorrelation.com/</a>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="wrangling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rmarkdown.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/05-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
